"""Add first and last name to User model

Revision ID: 043f0f693afa
Revises: 4ccb2d377b7d
Create Date: 2024-07-15 13:25:06.235607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '043f0f693afa'
down_revision = '4ccb2d377b7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=150), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'last_name')
    # ### end Alembic commands ###
