"""Make first_name and last_name non-nullable

Revision ID: f39cd61213dc
Revises: 043f0f693afa
Create Date: 2024-07-15 13:42:28.219249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f39cd61213dc'
down_revision = '043f0f693afa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'first_name', nullable=False)
    op.alter_column('user', 'last_name', nullable=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'first_name', nullable=True)
    op.alter_column('user', 'last_name', nullable=True)
    # ### end Alembic commands ###
